### ISSUE TITLE
AETHER CORP - Initiate

### ISSUE THREAD

**Issue by StealthAdder** [StealthAdder/Companies#13]
### AETHER Corp Website Build

_Nuclear fuel supplier company for nuclear power plants_  **(Improvise)**

Design template pending
**To do List**

- [x] Nav bar
- [x] Footer
- [x] add some contents

**Comment by StealthAdder** [comment]
Is the main page code structured ?@firedrakesin

**Comment by firedrakesin** [comment]
Naah........ need some more time @StealthAdder
